services:
    db:
        image: mysql:8.0.25
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: assesment_db
        ports:
            - "3307:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql:Z
        networks:
            - app_network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: assesment_app
        restart: unless-stopped
        working_dir: /var/www/php
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/php
        networks:
            - app_network
        depends_on:
            - db
        env_file:
            - .env

    webserver:
        image: nginx:latest
        container_name: assesment_webserver
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/php
            - ./docker/config/nginx:/etc/nginx/conf.d
        networks:
            - app_network
        depends_on:
            - app
        env_file:
            - .env
        tty: true

networks:
    app_network:
        driver: bridge

#volumes:
#    db_data:
